# Generated by Django 6.0.8 on 2026-08-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('batting_style', models.CharField(max_length=100)),
                ('bowling_style', models.CharField(max_length=100)),
                ('matches', models.PositiveIntegerField()),
                ('runs', models.PositiveIntegerField()),
                ('wickets', models.PositiveIntegerField()),
                ('biography', models.TextField()),
                ('image', models.ImageField(upload_to='players/')),
            ],
        ),
    ]
