# Generated by Django 6.0.8 on 2026-08-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
