# Generated by Django 6.0.8 on 2026-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='featured_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
